site_name: My Docs
site_url: https://sitename.example
theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
  font:
    text: Roboto
    code: Red Hat Mono
  palette:
    scheme: slate
    primary: indigo
    accent: orange
  features:
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.tabs
    - content.tooltips
    - content.code.annotate
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - abbr
  - md_in_html
  - tables
  - pymdownx.blocks.caption
extra:
  social:
    - icon: simple/linkedin
      name: squidfunk on Mastodon
      link: https://linkedin.com/in/darylics
copyright: Copyright &copy; 2024 Daryl CS
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js